### PR TITLE
Feature: add ability to search books

### PR DESCRIPTION
**Pull request by KevinLeighCrain**

### CODE REVIEW

**Comment by riggaroo** [comment]
Hi Kevin.
Thanks for this pull request. Searching for books is a good feature. The problem is that we are currently migrating to use Firebase for the backend. So the code on Master/Dev will soon differ greatly. I will be merging the Firebase feature branch in soon into dev, and then hopefully soon we can release a version of the app to the store of it. We are just currently working on migrating the backend data and doing some final tweaks of the backed. 
I wont merge this pull request as I said the code will change quite a lot. 
It would be great if you could implement search again on the Firebase stuff after it has been merged into dev. 
Thanks again!

**Comment by KevinLeighCrain** [comment]
@riggaroo Great! Noticed that firebase migration is taking place in project, good luck with that, Let me know when search functionality is ready to be implemented and I will proceed to implement search. If there are any specs etc. you can post me back and I will update too specification when ready.

Enjoy!

**Comment by riggaroo** [comment]
Hi @KevinLeighCrain

We have migrated to Firebase. If you are still up for it, you can do the searching with Firebase. I have created an issue - #16 check it out. I will add some wireframes of how it should work later today. Let me know if you are keen otherwise we will pick it up.

**Comment by KevinLeighCrain** [comment]
@riggaroo Thanks, glad to here the good news, yes I am still keen, will have a look into the issue `#16`

**Comment by KevinLeighCrain** [comment]
@riggaroo Let me know when you have re-opened the issue and I will be ready to help you guys out. Good luck

**Pull request closed without merging**
